server:
  port: 9898

#==============  redis  ========================
spring:
  redis:
    # Redis host ip
    host: 47.93.207.33
    # Redis 服务器连接端口
    port: 6379
    # Redis 数据库索引（默认为 0）
    database: 0
    # Redis 服务器连接密码（默认为空）
    password: ymkj666666
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/baiyu?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root